### ISSUE TITLE
Last item in list loses `task-overdue` class when an item above it is completed

### ISSUE THREAD

**Issue by darthmachina** [jamiebrynes7/obsidian-todoist-plugin#27] opened 2020-09-06 16:37 UTC
The last item in the list will lose the `task-overdue` CSS class when any item above it is completed and disappears. It's easy to see if the CSS has a special selector for that class (I have the overdue date turn red).

I believe this is actually cumulative, so the second to last item loses `task-overdue` if a second item is completed, but I haven't retested that. I have some overdue items I need to complete later today so I can verify that in a bit.

**Comment by jamiebrynes7** [comment] 2020-09-06 17:14
Hey @darthmachina I think I've found the cause of this, will verify and cut another patch release if so.

**Comment by jamiebrynes7** [comment] 2020-09-06 17:21
Alright, this should be fixed in [`v1.2.2`](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/v1.2.2)!

**Closed by jamiebrynes7** 2020-09-06 17:21 UTC
Labels: 🐛 bug
