### ISSUE TITLE
Compiled plugin return Function called outside component initialization error

### ISSUE THREAD

**Issue by KevinYobeth** [jamiebrynes7/obsidian-todoist-plugin#207] opened 2023-01-23 11:49 UTC
![image](https://user-images.githubusercontent.com/10485985/214032589-09a0bb78-6b07-4106-ad05-717678684e99.png)

**Comment by jamiebrynes7** [comment] 2023-02-07 19:09
Duplicate of #208

**Closed by jamiebrynes7** 2023-02-07 19:09 UTC
