### ISSUE TITLE
Commit as markdown on completion

### ISSUE THREAD

**Issue by mjsalam** [jamiebrynes7/obsidian-todoist-plugin#313] opened 2024-04-11 10:54 UTC
Is there an option (or if not would love if there was) to have a task render as markdown to a note upon completion.  

For example: When I complete a task (before it disappears) it gets rendered to a particular section in my daily note (## completed or something like that).

Thanks!  Awesome plugin!

**Comment by jamiebrynes7** [comment] 2024-07-19 15:53
Duplicate of https://github.com/jamiebrynes7/obsidian-todoist-plugin/issues/58

**Closed by jamiebrynes7** 2024-07-19 15:53 UTC
Labels: ✨ feature
