### ISSUE TITLE
get the error "Oh no, something went wrong"

### ISSUE THREAD

**Issue by mustachius** [jamiebrynes7/obsidian-todoist-plugin#157] opened 2022-04-05 11:59 UTC
I use Obsidian 0.14.2 and when creating a new note with the code block:

```todoist
{
"name": "My Tasks",
"filter": "today | overdue"
}
```

Instead of getting the Todoist task list, I get the message.

```
"Oh no, something went wrong!

Error: Forbidden
``` 

I've tried changing the filters to pt-br (Todoist's native language) but I've been unsuccessful.

**Comment by jamiebrynes7** [comment] 2022-04-09 18:11
Hey @mustachius, this error is reported from Todoist. I'd check the API token that you provided the plugin, if this was pasted incorrectly, I would expect this error message back.

**Comment by mcconnellj** [comment] 2022-08-25 18:41
@jamiebrynes7 I'm getting this same issue. I have confirmed that the API token was copied correctly. 

Any movement on this issue? Or some way I can pull logs to help?

**Comment by gnapse** [comment] 2022-09-23 16:36
I have this issue, and it seems a problem with Todoist's API. However, in my case I do not get a response of "Forbidden", but a 500 response instead. I tried with API v2 (see #176) in which case I get a 404 response. In any case, it does not work. It works with simpler filter strings such as `"filter": "today"`, but not with `"filter": "today | overdue"`.

I'll figure out with Todoist API developers why this is the case.

**Comment by jamiebrynes7** [comment] 2022-10-17 18:58
Hey @mcconnellj, @mustachius can you try the latest v1.10.0 release?

It contains the update to Todoist's REST API v2, which may resolve the issue

**Comment by mcconnellj** [comment] 2022-10-17 20:14
@jamiebrynes7 still seeing the error message on my side.

**Comment by Viibrant** [comment] 2022-11-28 11:56
I've also tried the newest release and am still getting this error.

**Comment by jamiebrynes7** [comment] 2022-12-23 16:22
Hey all, the latest release `v1.10.1`, also has a change to how requests are made that might resolve this issue. 

Let me know if you're still experiencing the issue

**Comment by mcconnellj** [comment] 2022-12-23 16:40
Still on this grind with you @jamiebrynes7 @Viibrant.

Mine is not working with the following versions.
Obsidian 1.1.8
Todoist Plugin 1.10.1

This is the query I'm using, I don't have a lot of experience so I figured I'd add it for review.

![ssCapture](https://user-images.githubusercontent.com/8952865/209369029-30266e4d-91c9-41b7-986d-35fbc1e36585.JPG)

**Comment by mcconnellj** [comment] 2022-12-23 16:41
@Viibrant what OS are you on? 

Windows 10 pro for me.

**Comment by mcconnellj** [comment] 2022-12-30 16:08
@jamiebrynes7 @Viibrant.

I'm getting off an on success. I believe my issue was not restarting the application after entering the API key. I take full accountability for not reading the instructions, my bad.

That being said I'm getting off and on 503 errors. I'll add more details if the plugin continues to misbehave. 

Much love my friends, 
Thank you for your help.

**Comment by Viibrant** [comment] 2022-12-30 16:19
Glad it's beginning to work for you @mcconnellj! I never did update ~

I'm on Ubuntu 22.04. After trying everything I refreshed my API token an unknown amount of times and that appears to have resolved it! Not sure why that worked and is very unsatisfying, but at least I can use it now :) Jolly good show!

**Comment by mcconnellj** [comment] 2022-12-30 18:21
@jamiebrynes7 this looks like a resolved bug. Not sure if this was already closed, if not it should be.

Unless of course, @gnapse or @mustachius are still having issues. No movement from them since before September though.

Cheers,
Josh

**Comment by jamiebrynes7** [comment] 2022-12-31 20:08
I'm happy to close this bug, if folks continue to hit this issue we can re-open it!

**Closed by jamiebrynes7** 2022-12-31 20:08 UTC
Labels: 🐛 bug
