### ISSUE TITLE
Project name that includes a certain special character (a 'caret' in this case) cannot be filtered correctly.

### ISSUE THREAD

**Issue by bnsonear** [jamiebrynes7/obsidian-todoist-plugin#209] opened 2023-01-24 12:59 UTC
**Describe the bug**
If a project name has any "caret" in its name, filter with starting # does not return the correct result when the project name has other spaces or emoji also. Internal use of a filter with that project name in the Todoist app (Windows) has no effect. This bug only occurs when using Todoist plugin in Obsidian (maybe API problem?)

**To Reproduce**
1. Rename the existing project in Todoist app (Windows) 
    add 'caret' in front of the name such as, from `"Project Planning" to "^Project Planning"`
2. change the filter in Obsidian  `"filter": "#Project Planning" to "filter": "#^Project Planning"`
3. Press reload button and wait
4. See the incorrect result: `Nothing to-do! Sit back and relax.`
5. You can find that `#^Project Planning"` is working normally = returns the correct result in Todoist app (Windows).

**Expected behavior**
Regardless of 'caret', plugin should show the correct result.

**Screenshots**

**Desktop (please complete the following information):**
 - Plugin Version: 1.10.1
 - Obsidian Version: 1.1.9

**Additional context**
Thank you for this great plugin!

**Comment by jamiebrynes7** [comment] 2024-02-01 19:34
Hey @bnsonear, I'm unable to reproduce this on the latest release. I have a project called `^Test` and both:

```yaml
name: ""
filter: "#^Test"
```

```json
{
	"name": "",
	"filter": "#^Test"
}
```

Produce the expected result. Given this was reported ~1 year ago, perhaps Todoist has closed this particular gap on their end in the API? 

In any case - I'm going to mark this as closed!

**Closed by jamiebrynes7** 2024-02-01 19:34 UTC
Labels: 🐛 bug
