### ISSUE TITLE
Send tasks from Obsidian to Todoist?

### ISSUE THREAD

**Issue by ineedmore** [jamiebrynes7/obsidian-todoist-plugin#62] opened 2020-11-14 11:36 UTC
Can your script do opposite - Send tasks from Obsidian to Todoist?

It would be awesome to start morning pages in Obsidian and write new task as they come into your mind, then send it to todoist for further control. The same with Worklog and Communicationlog. The idea is to use Obsidian as initial base for all thoughts, ideas and then use 3rd party apps for better results.

**Comment by jamiebrynes7** [comment] 2020-11-15 19:20
Hi @ineedmore, this seems like a duplicate of #43, if I'm not mistaken? 

If so, I'll fold this request into that one. I'm planning to implement some form of this in the next release 😁

**Comment by jamiebrynes7** [comment] 2020-12-09 20:13
Closing this as a duplicate of #43, feel free to re-open this with more information if you feel its sufficiently different!

**Closed by jamiebrynes7** 2020-12-09 20:13 UTC
Labels: ✨ feature
