### ISSUE TITLE
Option to show completed tasks

### ISSUE THREAD

**Issue by chippy** [jamiebrynes7/obsidian-todoist-plugin#361] opened 2024-12-02 16:29 UTC
I would really like to have the option to be able to show completed tasks as well as uncompleted ones.

**Comment by jamiebrynes7** [comment] 2024-12-15 18:31
Duplicate of https://github.com/jamiebrynes7/obsidian-todoist-plugin/issues/233

**Closed by jamiebrynes7** 2024-12-15 18:31 UTC
Labels: ✨ feature
