### ISSUE TITLE
Add tasks checked 'completed' to daily note

### ISSUE THREAD

**Issue by jensbri** [jamiebrynes7/obsidian-todoist-plugin#273] opened 2024-01-15 00:46 UTC
**Is your feature request related to a problem? Please describe.**
While the plugin works great, I'd like to get tasks that I click as completed to be added to my daily note.

**Describe the solution you'd like**
Currently, if I click a task complete, it just disappears from Obsidian.
I use the Day Planner plugin, meaning that I have a .md file for every day.
Ideally, I would like to see the tasks that I ticked completed not to just disappear, but to be listed below (in a section with the heading log or similar).

**Describe alternatives you've considered**
I could painfully copy each task's text. Paste it manually below. Then tick the task completed, but that is very cumbersome.

Thank you very much for either letting me know how to do it with the current state or considering this feature request.

**Comment by jnskender** [comment] 2024-01-22 14:51
Agreed, I like to review my daily notes to see what I accomplished on any given day.

**Comment by jamiebrynes7** [comment] 2024-02-01 20:34
Dupe of #58

**Closed by jamiebrynes7** 2024-02-01 20:34 UTC
Labels: ✨ feature
