### ISSUE TITLE
Right-Click 1.71 

### ISSUE THREAD

**Issue by ParzivalWins** [jamiebrynes7/obsidian-todoist-plugin#113] opened 2021-06-23 21:32 UTC
**Describe the bug**
Upgraded to latest version 1.71 and rendered view of todo items on Mac OS Obsidian 0.12.7 doesn't bring up context menu for link or completing. 

**To Reproduce**
1. Go to rendered task
2. Right Click on task. Only "Copy" appears
3. 

**Expected behavior**
Right clicking on a task will now open a context menu where you can either complete the task or open it in the browser or application.

**Screenshots**
Added.

**Desktop (please complete the following information):**
 - Plugin Version [e.g. 1.7.1
<img width="765" alt="Screen Shot 2021-06-23 at 2 30 40 PM" src="https://user-images.githubusercontent.com/25649258/123170673-a3b48400-d42f-11eb-8d46-91b8f506cf01.png">
]
 - Obsidian Version [e.g. 0.12.7]

**Additional context**

**Comment by jamiebrynes7** [comment] 2021-08-07 13:13
Hey @ParzivalWins, I'm unable to reproduce this on my (Windows) machine. It seems as though this might be a MacOS only bug?

Unfortunately, I don't have access to a MacOS machine to test on.

**Comment by jamiebrynes7** [comment] 2022-01-19 21:04
This might have been fixed in [v1.9.0](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/1.9.0) as the way the right-clicking menu was handled was changed. Going to close this for now, if this issues persists after upgrading, please reopen!

**Closed by jamiebrynes7** 2022-01-19 21:04 UTC
Labels: 🐛 bug
