### ISSUE TITLE
Slow Launch on iOS

### ISSUE THREAD

**Issue by JamieDaghaim** [jamiebrynes7/obsidian-todoist-plugin#364] opened 2024-12-10 13:06 UTC
**Describe the bug**
When launching Obsidian, Todoist Sync plugin takes many seconds to load (shortest is 1.2sec)

**To Reproduce**
Force close Obsidian on iOS then launch
Happens even if Obsidian is still open in background

**Expected behavior**
Either faster loading time
Or full sync once a day then manual for rest? 

**Screenshots**
Attached

**iPhone 16 Pro Max; iOS 18.2**
![IMG_1297](https://github.com/user-attachments/assets/387f4db6-579f-4658-88f5-0a1a743bc281)
![IMG_1296](https://github.com/user-attachments/assets/b8333190-4255-428f-9331-adc85c8d7c9d)
![IMG_1294](https://github.com/user-attachments/assets/aa9f42ff-a1ff-49f2-b88a-87a77930f381)

 - Plugin Version: 1.13
 - Obsidian Version: 1.7.7

**Additional context**

**Comment by jamiebrynes7** [comment] 2024-12-15 18:03
Duplicate of https://github.com/jamiebrynes7/obsidian-todoist-plugin/issues/347

**Closed by jamiebrynes7** 2024-12-15 18:03 UTC
Labels: 🐛 bug
