### ISSUE TITLE
Project filter just stopped working

### ISSUE THREAD

**Issue by fishcasa** [jamiebrynes7/obsidian-todoist-plugin#237] opened 2023-06-01 16:35 UTC
**Describe the bug**
code renders tasks from all different projects and priorities when it should just show p1 tasks for the project specified in the filter

**To Reproduce**
Go to live preview with code below inserted
If I remove the   "#Account Capture Activities Project & " it shows all p1 tasks correctly.

**Expected behavior**
show all priority 1 tasks for the project "Account Capture Activities Project" with this code

```
```todoist
name: Critical This Week (P1) Tasks
filter: "#Account Capture Activities Project & p1"
```

**Screenshots**
![download](https://github.com/jamiebrynes7/obsidian-todoist-plugin/assets/4305537/39de155d-4659-4ed8-8b74-9774202e9cac)

**Desktop (please complete the following information):**
 - Plugin Version v1.11.1
 - Obsidian Version v1.3.5

**Additional context**
Same behavior on Windows 10 and Windows 11

**Comment by jamiebrynes7** [comment] 2023-06-01 16:38
Closing as duplicate of #235

**Closed by jamiebrynes7** 2023-06-01 16:38 UTC
Labels: 🐛 bug
