### ISSUE TITLE
Cant Input API Token

### ISSUE THREAD

**Issue by BeAwaken** [jamiebrynes7/obsidian-todoist-plugin#362] opened 2024-12-06 04:33 UTC
**Describe the bug**
1. After Installing and Enabling de Plugin I am not prompted to Login the Token. I also cant access the Setup button as it appears a crossed circle indicating it cant be accessed. 
2. Even though i havent input my token, a green check mark appears besides the setup gear button.
3. I tried Uninstalling and istalling again with no success. 
Thats it.

**To Reproduce**
1. Followed your Documentation Step 1 Install Plugin successfully.
2. I had the Problem on Step 2 "Setup the API Token". I didnt get a Pop Up Asking me to input the API Token.
3. Not Possible to Click the Setup button.

**Expected behavior**
Get a Pop Up asking me to Access the API Token. Or being able to click and access the Setup Gear.

**Screenshots**

**Desktop (please complete the following information):**
 - Plugin Version [e.g. 1.13.0]
 - Obsidian Version [e.g. 1.7.7]

**Additional context**
![PXL_20241206_042328313](https://github.com/user-attachments/assets/8f4146ec-7b78-46f8-944b-d28eefd73961)

**Comment by tiovialde** [comment] 2024-12-11 10:42
@BeAwaken I had the same problem, and in my case, even though clicking left didn't work, the plugin accepted a new API when 
I clicked right. It only kind of worked because some filters are still broken in my case, even though I changed nothing in them.

**Comment by jamiebrynes7** [comment] 2024-12-15 18:29
Duplicate of https://github.com/jamiebrynes7/obsidian-todoist-plugin/issues/342

**Closed by jamiebrynes7** 2024-12-15 18:29 UTC
Labels: 🐛 bug
