### ISSUE TITLE
Create Todoist Task : Invalid date when clicking on arrows to go to January 2023

### ISSUE THREAD

**Issue by Banesmagic** [jamiebrynes7/obsidian-todoist-plugin#198] opened 2022-12-30 22:08 UTC
![84D3D6F2-13D5-4595-AA0D-8AE189FC1C46](https://user-images.githubusercontent.com/35113388/210114762-fa7e5f0a-caac-4897-a615-9133e82c50cc.jpeg)

**Comment by jamiebrynes7** [comment] 2022-12-31 20:05
Hey @Banesmagic, I'm unable to reproduce this issue, I'm able to cycle forward to Jan 2023 okay.

Did you just click the right arrow once? Or did you cycle back and forward to get into this state?

**Comment by Banesmagic** [comment] 2022-12-31 21:29
> Hey @Banesmagic, I'm unable to reproduce this issue, I'm able to cycle forward to Jan 2023 okay.
> 
> Did you just click the right arrow once? Or did you cycle back and forward to get into this state?

I was only clicking on the right arrow.  Forgot to mention that this was only happenning on mobile (iOS).  It does not occur on desktop.  Thanks for your very quick response!  Really appreciate all your great work.

**Comment by jpirgl** [comment] 2023-08-13 09:04
Hey, I am also still experiencing this issue on my iPad - calendar gets shown for December 2022, and when I click the right calendar arrow, it again shows the calender in October 2023, November 2023, December 2023. And then again "incorrect date". Attaching a set of screenshots.

I am on iPad Pro 2nd generation, plugin version 1.11.1, Obsidian version 1.4.6 (105)

Great plugin, though!!! Thanks for all the work!!!

![IMG_3352](https://github.com/jamiebrynes7/obsidian-todoist-plugin/assets/98642604/8cd24be4-40cc-41e3-8ab7-5d2409dae0b0)
![IMG_3354](https://github.com/jamiebrynes7/obsidian-todoist-plugin/assets/98642604/8016b67a-3050-4169-842a-8984eab8c99a)

![IMG_3353](https://github.com/jamiebrynes7/obsidian-todoist-plugin/assets/98642604/3e45324e-4773-4ddf-a2a4-5dc58ae643c0)

**Comment by darkwolfgar** [comment] 2024-03-18 20:24
Also experiencing this on IPad Pro, App version 1.5.8.

**Comment by jamiebrynes7** [comment] 2024-04-10 17:18
Hey all, I've rewritten the task creation modal in the [latest release](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/1.13.0). I'm no longer rolling my own calendar implementation, so hopefully this issue is no longer relevant.

I'm going to (optimistically) close this, but please do reopen this if you are still experiencing it.

**Closed by jamiebrynes7** 2024-04-10 17:18 UTC
Labels: 🐛 bug
