### ISSUE TITLE
Todoist Plugin Not Rendering in Live Preview Mode in Obsidian v0.13.4

### ISSUE THREAD

**Issue by lukthony** [jamiebrynes7/obsidian-todoist-plugin#138] opened 2021-12-22 05:16 UTC
**Describe the bug**
Obsidian introduced a Live Preview feature that renders elements and plugin code blocks in line. This does not work for this plugin. 

**To Reproduce**
1. Write a todoist plugin code block
2. Click outside of it
3. It isn't rendered.

**Expected behavior**
Rendered live into a functioning todoist task list.

**Screenshots**

Live Preview Mode:
<img width="709" alt="Screen Shot 2021-12-21 at 11 11 11 PM" src="https://user-images.githubusercontent.com/65358837/147039142-654b4f85-52bf-49e9-b156-92b092b273f1.png">

Preview Mode
<img width="728" alt="Screen Shot 2021-12-21 at 11 13 18 PM" src="https://user-images.githubusercontent.com/65358837/147039367-9bd745ef-1920-4b5c-a601-539d23f1bede.png">

**Desktop:**
 - Plugin Version 1.8.1
 - Obsidian Version 0.13.4

**Comment by aventuraviper** [comment] 2022-01-04 10:08
Have you tried again in 13.14? It works for me.

**Comment by ChrArendt** [comment] 2022-01-06 09:53
@aventuraviper It doesn't for me. Does it depend on the theme, or do you have a custom css for that?

**Comment by lukthony** [comment] 2022-01-07 07:52
> Have you tried again in 13.14? It works for me.

Just installed and checked the latest version—no dice. I'd echo what @ChrArendt said: do you have some sort of custom css that may be making it work when it otherwise wouldn't?

**Comment by matthew-langley** [comment] 2022-01-07 23:51
Does not work for me either, v0.13.19

**Comment by anvimea** [comment] 2022-01-08 04:33
Not working for me either, v0.13.19.

**Comment by kylestratis** [comment] 2022-01-10 22:56
Also not working for me, v.0.13.19

**Comment by aventuraviper** [comment] 2022-01-12 10:21
Apologies, I can confirm it is isn't working for me on v.0.13.19.

I usually use Todoist blocks by referencing them into another note using ![[note with todoist code block]]. These work fine in Live preview (are always rendered). I also had a pluigin swapping between edit and read that was taking me out of live preview and into reading mode when I tried to reproduce.

Again, apologies. 

Is this due to the Todoist block syntax perhaps? Other plugins that use blocks like this, such as tasks or Toggl, don't need curly braces or quote marks, so perhaps these trip the live preview mode into treating it as a regular block of code text?

**Comment by jamiebrynes7** [comment] 2022-01-12 18:26
Hey all, will take a look at this one over the weekend and try to get a fix out then!

**Comment by jamiebrynes7** [comment] 2022-01-19 20:11
Little update on this one: I've got it rendering in Live preview and the functionality seems to work, but the styling is all out of wack.  Weirdly it doesn't seem like anything to do with CSS, there's just extra spacing added between some of the divs.

**Comment by lukthony** [comment] 2022-01-19 20:14
That's good to hear! I've seen issues like this(spacing) happen with other plugins. I even [reported the issue for Admonition](https://github.com/valentine195/obsidian-admonition/issues/141). Not sure if it'll help, but maybe the way they fixed it will provide some manner of insight.

**Comment by jamiebrynes7** [comment] 2022-01-19 20:19
@lukthony that's perfect, seems to resolve most, if not all the issues, will do some further testing and then cut a release!

**Comment by lukthony** [comment] 2022-01-19 20:20
Glad to help. Thanks for everything.

**Comment by jamiebrynes7** [comment] 2022-01-19 20:59
Hey all, this should be fixed in [v1.9.0](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/1.9.0), let me know if you notice regressions. You may need to adjust any custom CSS accordingly!

**Closed by jamiebrynes7** 2022-01-19 20:59 UTC
Labels: 🐛 bug
